AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Resources:
  TestFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: index.handler
      Runtime: nodejs8.10
      Environment:
        Variables:
          S3_BUCKET: acloudguru-cfsambucket
      CodeUri: s3://acloudguru-cfsambucket/d211108fcd40b082fb622cb7244bf06c
