AWSTemplateFormatVersion: '2010-09-09'
Resources:
  TestFunction:
    Properties:
      CodeUri: s3://cfsambucket-faye/5c69705d60312a253e72f31ba8204df3
      Environment:
        Variables:
          S3_BUCKET: cfsambucket-faye
      Handler: index.handler
      Runtime: nodejs8.10
    Type: AWS::Serverless::Function
Transform: AWS::Serverless-2016-10-31
